config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  get 'static_pages/home'
  get 'static_pages/show'
  root "static_pages#home"

  devise_for :users, :controllers => { registrations: 'registrations'}

  resources :searches

  get "/articles", to: "articles#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :correct_usertype
    validates :name, presence: true
    validates :email, presence: true

    def correct_usertype
        # Matches user booleans based on userType.  NOTE: May be more dynamic as a hash?
        if self.venue
            self.update_attribute(:usertype, "Venue") # update_attribute should not be the final answer. Loose reason is that
        elsif self.vendor                             # it bypasses validation, which is not safe for a production environment.
            self.update_attribute(:usertype, "Vendor")
        elsif self.event
            self.update_attribute(:usertype, "Event")
        elsif self.press
            self.update_attribute(:usertype, "Press")
        else
            self.update_attribute(:standard, true)
            self.update_attribute(:usertype, "Attendee")
        end
    end

    def correct_userbool
        # Matches userType based on user booleans.  NOTE: May be more dynamic as a hash?
        case self.usertype
        when "Attendee"
            self.update_attribute(:standard, true)

            self.update_attribute(:venue, false)
            self.update_attribute(:vendor, false)
            self.update_attribute(:event, false)
            self.update_attribute(:press, false)
        when "Venue"
            self.update_attribute(:venue, true)

            self.update_attribute(:vendor, false)
            self.update_attribute(:event, false)
            self.update_attribute(:press, false)
            self.update_attribute(:standard, false)
        when "Vendor"
            self.update_attribute(:vendor, true)
            
            self.update_attribute(:standard, false)
            self.update_attribute(:venue, false)
            self.update_attribute(:event, false)
            self.update_attribute(:press, false)
        when "Event"
            self.update_attribute(:event, true)
            
            self.update_attribute(:press, false)
            self.update_attribute(:standard, false)
            self.update_attribute(:venue, false)
            self.update_attribute(:vendor, false)
        when "Press"
            self.update_attribute(:press, true)
            
            self.update_attribute(:standard, false)
            self.update_attribute(:venue, false)
            self.update_attribute(:vendor, false)
            self.update_attribute(:event, false)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if logged_in?
      @users = User.all
      # @users = User.search(params[:search])
      # @users = User.paginate(page: params[:page])
    else
      redirect_to new_session_path
    end
  end

  # GET /users/1 or /users/1.json
  def show
    if logged_in?

    else
      redirect_to new_session_path
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if logged_in?

    else
      redirect_to new_session_path
    end
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.correct_userbool

    if @user.save
      flash[:notice] = "User created." 
      redirect_to root_path
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if logged_in?
      respond_to do |format|
        if @user.update(user_params)
          @user.correct_userbool
          format.html { redirect_to @user, notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_session_path
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if logged_in?
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to new_session_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :zip, :address, :usertype)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <br>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <br>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <br>
    <%= form.text_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <br>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <br>
    <%= form.text_field :zip%>
  </div>

  <label for="usertype">Account Type</label>

  <%= form.select :usertype, ["Attendee", "Venue", "Vendor", "Event", "Press"] %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_menu.html.erb
<div class="menu">
<ul>
<li><%= link_to 'Home', static_pages_home_path %></li>
<% if logged_in? %>
  <li><%= link_to 'Connect', users_path%></li>
  <li><%= link_to "Advanced Search", new_search_path %></li>
  <li><%= link_to 'Logout', logout_path, method: :delete%></li>
<% else %>
  <li><%= link_to 'Login', new_session_path %></li>
  <li><%= link_to 'New User', new_user_path %></li>
<% end %>
</ul>
</div>

app/views/users/edit.html.erb
<%= render 'menu' %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'menu' %>

<h1>Users</h1>

<%= link_to "Advanced Search", new_search_path %>

<%= link_to 'New User', new_user_path %>
<table class="usercard">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
  <tbody>
      <tr>
        <td><%= user.usertype %></td>
      </tr>
      <tr>
        <td><%= user.name %></td>
      </tr>
      <tr>
        <td><%= user.email %></td>
      </tr>
      <tr>
        <td><%= user.describe %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', user %> | <%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/users/new.html.erb
<%= render 'menu' %>

<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'menu' %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @user.zip %>
</p>

<p>
  <strong>Admin?</strong>
  <%= @user.admin? %>
</p>

<p>
  <strong>Event?</strong>
  <%= @user.event? %>
</p>

<p>
  <strong>Venue?</strong>
  <%= @user.venue? %>
</p>

<p>
  <strong>Press?</strong>
  <%= @user.press? %>
</p>

<p>
  <strong>Vendor?</strong>
  <%= @user.vendor? %>
</p>

<p>
  <strong>Standard?</strong>
  <%= @user.standard? %>
</p>

<p>
  <strong>Activated?</strong>
  <%= @user.activated %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<p>
  <strong>User Type:</strong>
  <%= @user.usertype %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @user.updated_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>